### PR TITLE
Fix #120 - traverse single-node BVH

### LINKED ISSUE #120: `Bvh::traverse` produces incorrect results
The following test case fails but should pass:
```rust
    #[test]
    fn test_traverse_subtle_bvh() {
        let mut boxes = vec![
            UnitBox::new(0, TPoint3::new(0.0, 1.0, 2.0)),
        ];
        let ray = Ray::new(
            TPoint3::new(0.0, 0.0, 0.0),
            SVector::<f32, 3>::new(1.0, 0.0, 0.0),
        );

        let bvh = Bvh::build(&mut boxes);

        let found = bvh.traverse(&ray, &boxes);
        assert_eq!(found.len(), 0);
    }
```
The ray trivially misses the unit-cube:

Screenshot from 2025-01-06 20-23-16

### PR DESCRIPTION
**Pull request by finnbear**
Single-node BVH's are a special case since the root node is a leaf node. All traversal types, except flat, were unconditionally returning leaf nodes that they processed because they incorrectly assumed only intersected child leaf would be processed.

Fixes #120 and asserts, via the fuzzer, that traversal (which is now correct) agrees with flat traversal (which was correct).

Superficially conflicts with #128 and that PR is bigger, so recommend merging that PR first to make it easier to fix conflicts.

### CODE REVIEW

File: src/bvh/iter.rs [hunk 1]
```diff
@@ -33,7 +33,14 @@ impl<'bvh, 'shape, T: BHValue, const D: usize, Shape: Bounded<T, D>>
...
             stack_size: 0,
-            has_node: !bvh.nodes.is_empty(),
+            has_node: match bvh.nodes.first() {
+                // Only process the root leaf node if the shape's AABB is intersected.
+                Some(BvhNode::Leaf { shape_index, .. }) => {
+                    ray.intersects_aabb(&shapes[*shape_index].aabb())
+                }
+                Some(_) => true,
+                None => false,
+            },
```
Comment (svenstaro) [inline src/bvh/iter.rs:43]: Please pull this out of the construction statement and just place it above and store the value in a `has_node` variable. Should make it a bit more readable. I don't like it when the construction itself has too much logic in it. The previous logic here was fine because it wasn't much code.

File: src/bvh/iter.rs [hunk 2]
```diff
@@ -33,7 +33,14 @@ impl<'bvh, 'shape, T: BHValue, const D: usize, Shape: Bounded<T, D>>
             stack: [0; 32],
             node_index: 0,
             stack_size: 0,
-            has_node: !bvh.nodes.is_empty(),
+            has_node: match bvh.nodes.first() {
+                // Only process the root leaf node if the shape's AABB is intersected.
```
Comment (svenstaro) [inline src/bvh/iter.rs:37]: Maybe provide some reasoning here _why_ this is a good idea (even if it seems obvious to you).

File: src/bvh/distance_traverse.rs [hunk 3]
```diff
@@ -50,7 +50,14 @@ where
...
             stack_size: 0,
-            has_node: !bvh.nodes.is_empty(),
+            has_node: match bvh.nodes.first() {
+                // Only process the root leaf node if the shape's AABB is intersected.
+                Some(BvhNode::Leaf { shape_index, .. }) => {
+                    ray.intersects_aabb(&shapes[*shape_index].aabb())
+                }
+                Some(_) => true,
+                None => false,
+            },
```
Comment (svenstaro) [inline src/bvh/distance_traverse.rs:60]: See comments in `src/bvh/iter.rs`.

File: src/bvh/bvh_impl.rs [hunk 4]
```diff
@@ -107,7 +107,17 @@ impl<T: BHValue, const D: usize> Bvh<T, D> {
             return Vec::new();
         }
         let mut indices = Vec::new();
-        BvhNode::traverse_recursive(&self.nodes, 0, ray, &mut indices);
+        // Manually handle the case of a single-node BVH, because `traverse_recursive`
+        // cannot access the root shape's AABB.
```
Comment (svenstaro) [inline src/bvh/bvh_impl.rs:111]: We _could_ change this I suppose and give `traverse_recursive()` a reference to the root _in theory_. I'm not sure it would be cleaner in the end. What do you think? We could even give it `&self` and make the `BvhNode` carry a reference to the root (though this would probably be a large change and I'm not sure it's even useful).

**Review by svenstaro — CHANGES_REQUESTED** [review]

File: src/bvh/bvh_impl.rs (hunk 4 above)
Comment (finnbear) [reply src/bvh/bvh_impl.rs:111]: I would have done that except for the fact that `traverse_recursive` is public-API. AFAIK it shouldn't be. If you're fine with privatizing it, I'd make this change.

Comment (svenstaro) [reply src/bvh/bvh_impl.rs:111]: That's a good point. I don't see a reason people should use `traverse_recursive` directly over `traverse`.

File: src/bvh/iter.rs (hunk 2 above)
Comment (finnbear) [reply src/bvh/iter.rs]: Since this logic was duplicated, and I didn't want to also duplicate the comment, I abstracted this into a function.

File: src/bvh/distance_traverse.rs (hunk 3 above)
Comment (finnbear) [reply src/bvh/distance_traverse.rs]: Made a function to handle both :)

**Comment by svenstaro** [comment]
Man, you're really cleaning house. :)
